auto: true
server: true
permalink: /:categories/:title
baseurl: /tunisia-election-data
github: "http://github.com/fwelections/databrowser"
languages:
  - name: 'English'
    key: 'en'
  - name: 'French'
    key: 'fr'
  - name: 'Arabic'
    key: 'ar'
